---
before_script:
  - "wget http://services.gradle.org/distributions/gradle-1.3-bin.zip"
  - "unzip gradle-1.3* > /dev/null"
script: "gradle-1.3*/bin/gradle clean gaeDownloadSdk gaeExplodeWar minifyFridgeCss minifyFridgeJs"